CREATE TABLE parkings (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(50) NOT NULL,
                          street VARCHAR2(100) NOT NULL,
                          city VARCHAR2(50) NOT NULL,
                          state VARCHAR2(50) NOT NULL,
                          postal_code VARCHAR2(20) NOT NULL,
                          complement VARCHAR2(20),
                          available_area NUMBER NOT NULL,
                          capacity NUMBER NOT NULL,
                          structure_plan CLOB NOT NULL,
                          floor_plan CLOB NOT NULL,
                          map_plan CLOB NOT NULL
);
