CREATE TABLE motorcycles (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             license_plate VARCHAR2(10) NOT NULL UNIQUE,
                             model VARCHAR2(50),
                             chassis_number VARCHAR2(100),
                             operational_status VARCHAR2(50),
                             mechanical_condition VARCHAR2(50),
                             parking_id NUMBER NOT NULL,
                             CONSTRAINT fk_motorcycles_parkings FOREIGN KEY (parking_id)
                                 REFERENCES parkings(id)
);
