CREATE TABLE beacons (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         beacon_code VARCHAR2(36) NOT NULL,
                         beacon_status VARCHAR2(50),
                         motorcycle_id NUMBER,
                         CONSTRAINT fk_beacon_motorcycle FOREIGN KEY (motorcycle_id)
                             REFERENCES motorcycles(id)
);