CREATE TABLE employees (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR2(100) NOT NULL,
                           cpf VARCHAR2(14) NOT NULL UNIQUE,
                           birth_date DATE NOT NULL,
                           email VARCHAR2(100) NOT NULL UNIQUE,
                           role VARCHAR2(50) NOT NULL,
                           password VARCHAR2(200) NOT NULL,
                           parking_id NUMBER NOT NULL,
                           CONSTRAINT fk_employees_parkings FOREIGN KEY (parking_id)
                               REFERENCES parkings(id) ON DELETE CASCADE
);